---
title: "VS Code Extensions Everyone Should Have"

author: "Allison Day"
date: "4/20/2023"
categories: [VS Code]

draft: true
---

# Why VS Code?

Visual Studio Code was originally written to be web - based. Thus it feel so light. Here are some extensions that took my coding to the next level.

I've been using VS Code my whole coding career, nearly 5 years. I'm by no means a pro but I have picked up a few things along the way.

# My Extensions

## General Quality of Life

These are the extensions that improve VS Code as a whole. These are also the "optional" extensions that I use the most *(i.e. not required to function like Python or Git)*.

### [Better Comments](https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments)

As you can see by the whole section dedicated to themes, I'm a visual person. So an extension that can visually differentiate intentions between comments was a game changer. Now I can visually see the difference between warning and todo comments. Cannot recommend enough.

### [Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks)

This lets you put bookmarks throughout your scripts. This really helps with navigation, but I also used it to keep track of what I want to work on next and make a todo list. It also adds a bookmark page on the action bar. However, now that I usually use Jupyter Notebooks I don't personally use this extension as much as I used to.

### [Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare)

If you work with other people, especially remotely like I do, this tool is indispensable. It lets you both edit the same file or files at the same time. Took coding meetings from tedious backseat driving (click here, type this) to fun and productive collaboration sessions and cut the time in half. It even automatically includes their handle as a co-author in any git commits!

### [TabOut](https://marketplace.visualstudio.com/items?itemName=albert.TabOut)

If you only get one extension from this article, this is it.

Instead of using right arrows to get out of parenthesis, brackets, or quotes you just hit tab. You don't need to lift your hand from the keyboard to hit the arrow keys, you just reach up and tab out. It nearly brought me to tears the first time I used it. Cannot recommend enough.

## Themes

These affect the look of VS Code from colors to icons.

### Color Themes

Every time I open VS Code the first thing I do is hit `Ctrl + K` & `Ctrl + T` to change the visual theme to match my mood. I have come to discover that my mood linked to my environment, and that doesn't end at my decor. If I like looking at my code I like coding more.

-   [Bearded Theme](https://marketplace.visualstudio.com/items?itemName=BeardedBear.beardedtheme) -\
    Favorite:
    -   
-   [Noctis](https://marketplace.visualstudio.com/items?itemName=liviuschera.noctis) -\
    Favorite:
    -   
-   [Rainglow](https://marketplace.visualstudio.com/items?itemName=daylerees.rainglow) -\
    Favorite:
    -   

### [Material Icon Theme](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme) & [Material Product Icons](https://marketplace.visualstudio.com/items?itemName=PKief.material-product-icons)

These themes change the look of VS Code interface itself. These themes never change.

I love the Material Icon Theme because not only does it change the icons to differentiate file types but it also changes folder icons depending on its name. I love this extension so much that I have gone back through all of my repos and changed folder names to fit with this extension. But if Material Icon Theme is overwhelming or not to your taste I also recommend the [Bearded Icons](https://marketplace.visualstudio.com/items?itemName=BeardedBear.beardedicons) from the same developer as Bearded Theme.

Honestly, I just use Product Icons because for consistency. It's not important but shows VS Code's flexibility.

## Git & GitHub

### [GitHub Pull Requests and Issues](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github)

### [GitHub Copilot](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot) *(\*requires subscription)*

::: {.callout-note appearance="simple"}
Free Alternative: [IntelliCode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode) & [IntelliCode API Usage Examples](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.intellicode-api-usage-examples)
:::

### [GitLense](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) *(\*requires subscription)*

## Coding

### [Pylint](https://marketplace.visualstudio.com/items?itemName=ms-python.pylint)

### [Python Indent](https://marketplace.visualstudio.com/items?itemName=KevinRose.vsc-python-indent)

### Documentation: [autoDocstring](https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring) & [Python Type Hint](https://marketplace.visualstudio.com/items?itemName=njqdev.vscode-python-typehint)

This amazing extension auto populates the information of any Python function. Small things like this make documentation so much faster and easier - meaning I'll actually do it. Here's an example

``` python
def new_function():
    """
    """
    pass
```

### Formatters: [Black](https://marketplace.visualstudio.com/items?itemName=ms-python.black-formatter) *(python & jupyter) &* [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)

### Markdown: [All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one), [Checkboxes](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox), & [Lint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)

::: {.callout-tip appearance="simple"}
Install this [Markdown Extension Pack](https://marketplace.visualstudio.com/items?itemName=bat67.markdown-extension-pack) to get all of these extensions and more!
:::

## Data Science

### [Excel Viewer](https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer)

### [SandDance](https://marketplace.visualstudio.com/items?itemName=msrvida.vscode-sanddance) for VSCode

### [Quarto](https://marketplace.visualstudio.com/items?itemName=quarto.quarto)

::: {.callout-tip appearance="simple"}
Edit your posts in `Visual Mode` - right click in the document and select `Visual Mode`. Turns Visual Studio code into an actual document editor and lets you do fancy things like insert and edit tables, format, add links, and so much more! *(This works with any markdown document, not just Quarto!)*
:::

# Discover More Extensions