project:
  type: website
  output-dir: docs
  
website:
  title: "allisonbday.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/allison-b-day/

format:
  html:
    theme: 
    # - pulse
    - custom.scss
    css: styles.css



