project:
  type: website
  output-dir: docs
  
website:
  title: "allisonbday.github.io"
  favicon: "favicon.ico"
  reader-mode: true
  page-footer: "© 2023 Allison Day"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/allison-b-day/

format:
  html:
    theme: 
    # - pulse
    - style/custom.scss
    css: style/styles.css
    # toc: true
    # toc-location: left



