project:
  type: website
  output-dir: docs
  
website:
  title: "allisonbday.github.io"
  favicon: "https://em-content.zobj.net/source/animated-noto-color-emoji/356/dizzy_1f4ab.gif"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/allison-b-day/

format:
  html:
    theme: 
    # - pulse
    - custom.scss
    css: styles.css
    # toc: true
    # toc-location: left



