project:
  type: website
  output-dir: docs
  
website:
  title: "Allison Day"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/allison-b-day/

format:
  html:
    theme: pulse
    css: styles.css



