project:
  type: website

website:
  title: "Allison's Senior Project"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/allisonbday
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css



